const FULL_APPLICATION_NOTE = 'Full application = type set to "Full" with both a tailored CV and motivation letter.';
const DAILY_PLATFORM_NOTE = 'Platform diversity (daily) = use 3 or more distinct platforms today.';
const WEEKLY_PLATFORM_NOTE = 'Platform diversity (weekly) = use 6 or more distinct platforms this week.';

const DAILY_TOTAL_REWARD = { gold: 100, xp: 550 };
const WEEKLY_TOTAL_REWARD = { gold: 200, xp: 1000 };

const DAILY_CORE_IDS = ['D-APPS', 'D-FULL', 'D-PLATFORMS', 'D-CVS', 'D-LETTERS', 'D-COLD'];
const WEEKLY_CORE_IDS = ['W-APPS80', 'W-FULL35', 'W-PLATFORMS', 'W-STREAK', 'W-CVS', 'W-LETTERS', 'W-SKILL'];

export const QUESTS = {
  Daily: [
    {
      id: 'daily-definitions',
      type: 'note',
      title: 'Key definitions',
      notes: [
        FULL_APPLICATION_NOTE,
        'Daily 100% = finish every Daily core quest.',
        'Weekly 100% = finish every Weekly core quest.',
        DAILY_PLATFORM_NOTE,
        WEEKLY_PLATFORM_NOTE,
      ],
    },
    {
      id: 'daily-summary',
      type: 'summary',
      summaryKey: 'dailyTotals',
      title: "Today's rewards",
      desc: 'Finish every core quest to collect 100 gold and 550 XP.',
      totals: DAILY_TOTAL_REWARD,
    },
    {
      id: 'D-APPS',
      type: 'tiered',
      category: 'Daily core quest',
      title: 'Apply today',
      desc: 'Quantity drive.',
      tracking: {
        scope: 'daily',
        metric: 'applications',
        goal: 20,
        incremental: true,
        thresholds: [10, 15, 20],
      },
      tiers: [
        { id: 'D-APPS-10', value: 10, goal: 'Submit 10 applications today.', reward: { gold: 10, xp: 50 } },
        { id: 'D-APPS-15', value: 15, goal: 'Submit 15 applications today.', reward: { gold: 10, xp: 50 } },
        { id: 'D-APPS-20', value: 20, goal: 'Submit 20 applications today.', reward: { gold: 10, xp: 50 } },
      ],
      notes: ['Rewards stack because the quest is incremental (total 30 gold / 150 XP).'],
    },
    {
      id: 'D-FULL',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Full applications',
      desc: 'Depth matters.',
      goals: ['Submit at least 5 full applications today.'],
      tracking: {
        scope: 'daily',
        metric: 'fullApplications',
        goal: 5,
      },
      reward: { gold: 20, xp: 100 },
      notes: ['Full application uses the definition above.'],
    },
    {
      id: 'D-PLATFORMS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Platform diversity',
      goals: ['Use 3 or more distinct job platforms today.'],
      tracking: {
        scope: 'daily',
        metric: 'platforms',
        goal: 3,
      },
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-CVS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Tailored CVs',
      goals: ['Tailor at least 5 CVs today.'],
      tracking: {
        scope: 'daily',
        metric: 'tailoredCVs',
        goal: 5,
      },
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-LETTERS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Letters of motivation',
      goals: ['Write at least 5 motivation letters today.'],
      tracking: {
        scope: 'daily',
        metric: 'letters',
        goal: 5,
      },
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-COLD',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Cold approaches',
      goals: ['Complete 2 cold approaches today (LinkedIn or other).'],
      tracking: {
        scope: 'daily',
        metric: 'coldApproaches',
        goal: 2,
        manualKey: 'coldOutreach',
      },
      reward: { gold: 10, xp: 50 },
      actions: [{ type: 'log', key: 'coldOutreach', label: 'Log outreach' }],
      notes: ['Use the quick log button if auto detection is unavailable.'],
    },
    {
      id: 'D-PERFECT',
      type: 'standard',
      category: 'Daily mastery',
      title: 'Daily 100%',
      goals: ['Complete every other Daily quest.'],
      tracking: {
        scope: 'daily',
        metric: 'dailyPerfect',
        goal: 1,
        requires: DAILY_CORE_IDS,
      },
      reward: { gold: 10, xp: 100 },
      lock: 'Auto completes only when every other Daily quest is finished.',
      notes: ['Completing this quest increments the Daily streak counter.'],
    },
  ],
  Weekly: [
    {
      id: 'weekly-definitions',
      type: 'note',
      title: 'Weekly structure',
      notes: [
        'Core quests reset each week. Finish them all to unlock Weekly 100%.',
        'Cyclable slots per week: choose any two quests that fit your focus.',
        WEEKLY_PLATFORM_NOTE,
      ],
    },
    {
      id: 'weekly-summary',
      type: 'summary',
      summaryKey: 'weeklyTotals',
      title: 'Weekly rewards',
      desc: 'Complete every core quest to claim 200 gold and 1000 XP this week.',
      totals: WEEKLY_TOTAL_REWARD,
    },
    {
      id: 'weekly-overview',
      type: 'summary',
      summaryKey: 'weeklyProgress',
      title: 'Weekly progress',
      desc: 'Track Weekly 100% progress and optional slot usage.',
    },
    {
      id: 'weekly-core-section',
      type: 'section',
      title: 'Core quests',
      subtitle: 'Complete the full set to earn Weekly 100%.',
    },
    {
      id: 'W-APPS80',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly volume',
      goals: ['Submit at least 80 applications this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'applications',
        goal: 80,
      },
      reward: { gold: 50, xp: 250 },
    },
    {
      id: 'W-FULL35',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly full apps',
      goals: ['Submit at least 35 full applications this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'fullApplications',
        goal: 35,
      },
      reward: { gold: 30, xp: 150 },
      notes: ['Full application uses the definition above.'],
    },
    {
      id: 'W-PLATFORMS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly platform diversity',
      goals: ['Use 6 or more distinct platforms this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'platforms',
        goal: 6,
      },
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'W-STREAK',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Daily streak carry',
      goals: ['Earn Daily 100% on at least 4 days this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'dailyPerfectDays',
        goal: 4,
      },
      reward: { gold: 20, xp: 100 },
      notes: ['Daily 100% completions feed this quest automatically.'],
    },
    {
      id: 'W-CVS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly tailored CVs',
      goals: ['Tailor at least 25 CVs this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'tailoredCVs',
        goal: 25,
      },
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'W-LETTERS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly letters',
      goals: ['Write at least 25 motivation letters this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'letters',
        goal: 25,
      },
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'W-SKILL',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Skill growth',
      goals: ['Log at least 1 new skill learning activity this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'skillLearning',
        goal: 1,
        manualKey: 'skillLearning',
      },
      reward: { gold: 15, xp: 75 },
      actions: [{ type: 'log', key: 'skillLearning', label: 'Log activity' }],
      notes: ['Use the quick log button when telemetry is missing.'],
    },
    {
      id: 'W-PERFECT',
      type: 'standard',
      category: 'Weekly mastery',
      title: 'Weekly 100%',
      goals: ['Complete every Weekly core quest.'],
      tracking: {
        scope: 'weekly',
        metric: 'weeklyPerfect',
        goal: 1,
        requires: WEEKLY_CORE_IDS,
      },
      reward: { gold: 30, xp: 150, chest: 'Rare' },
      lock: 'Auto completes only when every Weekly core quest is finished.',
      notes: ['Completing this quest increments the Weekly 100% streak counter.'],
    },
    {
      id: 'weekly-cyclables-section',
      type: 'section',
      title: 'Cyclable quests',
      subtitle: 'Pick any two each week for additional rewards.',
    },
    {
      id: 'WC-RECRUITERS',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'Recruiter outreach',
      goals: ['Reach out to at least 10 recruiters this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'recruiterOutreach',
        goal: 10,
        manualKey: 'recruiterOutreach',
      },
      reward: { gold: 20, xp: 100 },
      actions: [{ type: 'log', key: 'recruiterOutreach', label: 'Log outreach' }],
      notes: ['Counts outreach logs flagged as recruiter contacts.'],
    },
    {
      id: 'WC-AGENCIES',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'Agency check-ins',
      goals: ['Contact at least 3 recruiter agencies this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'agencyContacts',
        goal: 3,
        manualKey: 'agencyContacts',
      },
      reward: { gold: 15, xp: 75 },
      actions: [{ type: 'log', key: 'agencyContacts', label: 'Log agency' }],
    },
    {
      id: 'WC-NETWORK',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'Network pings',
      goals: ['Request at least 3 introductions from friends this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'networkPings',
        goal: 3,
        manualKey: 'networkPing',
      },
      reward: { gold: 20, xp: 100 },
      actions: [{ type: 'log', key: 'networkPing', label: 'Log ping' }],
      notes: ['Use the quick log when no data source is available.'],
    },
    {
      id: 'WC-CITIES',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'City targeting',
      goals: ['Target at least 4 distinct cities this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'cities',
        goal: 4,
      },
      reward: { gold: 20, xp: 100 },
      notes: ['Counts distinct city fields on applications logged this week.'],
    },
    {
      id: 'WC-REFERRALS',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'Referral pipeline',
      goals: ['Submit at least 2 referral applications this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'referralApplications',
        goal: 2,
      },
      reward: { gold: 20, xp: 100 },
      notes: ['Auto counts applications logged with referral status or flag.'],
    },
    {
      id: 'WC-PORTFOLIO',
      type: 'standard',
      category: 'Weekly cyclable quest',
      title: 'Portfolio pulse',
      goals: ['Publish or update a portfolio item this week.'],
      tracking: {
        scope: 'weekly',
        metric: 'portfolioUpdate',
        goal: 1,
        manualKey: 'portfolioUpdate',
      },
      reward: { gold: 15, xp: 75 },
      actions: [{ type: 'log', key: 'portfolioUpdate', label: 'Toggle update' }],
    },
  ],
  Growth: [
    {
      id: 'growth-overview',
      type: 'note',
      title: 'Career growth',
      notes: [
        'Milestones track lifetime contributions.',
        'Level questlines unlock new objectives at key levels; use quick logs when telemetry is missing.',
      ],
    },
    {
      id: 'growth-milestones',
      type: 'section',
      title: 'Milestone chains',
      subtitle: 'Lifetime totals that keep growing.',
    },
    {
      id: 'LIFE-APPS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime applications',
      tracking: { scope: 'lifetime', metric: 'applications' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-APPS-100', value: 100, goal: 'Log 100 total applications.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-APPS-250', value: 250, goal: 'Log 250 total applications.', reward: { gold: 50, xp: 350, chest: 'Rare' } },
        { id: 'LIFE-APPS-500', value: 500, goal: 'Log 500 total applications.', reward: { gold: 100, xp: 700, chest: 'Epic' } },
        { id: 'LIFE-APPS-1000', value: 1000, goal: 'Log 1000 total applications.', reward: { gold: 250, xp: 1500, chest: 'Legendary' } },
      ],
    },
    {
      id: 'LIFE-FULL',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime full applications',
      tracking: { scope: 'lifetime', metric: 'fullApplications' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-FULL-50', value: 50, goal: 'Submit 50 full applications.', reward: { gold: 30, xp: 150 } },
        { id: 'LIFE-FULL-150', value: 150, goal: 'Submit 150 full applications.', reward: { gold: 80, xp: 400, chest: 'Rare' } },
        { id: 'LIFE-FULL-300', value: 300, goal: 'Submit 300 full applications.', reward: { gold: 150, xp: 900, chest: 'Epic' } },
      ],
    },
    {
      id: 'LIFE-COMBO',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Full + CV + letter combos',
      tracking: { scope: 'lifetime', metric: 'perfectCombos' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-COMBO-25', value: 25, goal: 'Complete 25 full combo applications.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-COMBO-75', value: 75, goal: 'Complete 75 full combo applications.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-COMBO-150', value: 150, goal: 'Complete 150 full combo applications.', reward: { gold: 150, xp: 900, chest: 'Epic' } },
      ],
    },
    {
      id: 'LIFE-CVS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Tailored CVs',
      tracking: { scope: 'lifetime', metric: 'tailoredCVs' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-CVS-50', value: 50, goal: 'Tailor 50 CVs.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-CVS-150', value: 150, goal: 'Tailor 150 CVs.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-CVS-300', value: 300, goal: 'Tailor 300 CVs.', reward: { gold: 150, xp: 900, chest: 'Epic' } },
      ],
    },
    {
      id: 'LIFE-LETTERS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Motivation letters',
      tracking: { scope: 'lifetime', metric: 'letters' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-LETTERS-50', value: 50, goal: 'Write 50 motivation letters.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-LETTERS-150', value: 150, goal: 'Write 150 motivation letters.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-LETTERS-300', value: 300, goal: 'Write 300 motivation letters.', reward: { gold: 150, xp: 900, chest: 'Epic' } },
      ],
    },
    {
      id: 'LIFE-CITIES',
      type: 'chain',
      category: 'Milestone chain',
      title: 'City coverage',
      tracking: { scope: 'lifetime', metric: 'cities' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-CITIES-10', value: 10, goal: 'Target 10 distinct cities.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-CITIES-20', value: 20, goal: 'Target 20 distinct cities.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-CITIES-35', value: 35, goal: 'Target 35 distinct cities.', reward: { gold: 150, xp: 900, chest: 'Epic' } },
      ],
    },
    {
      id: 'LIFE-DAYS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Active days',
      tracking: { scope: 'lifetime', metric: 'dailyPerfectCompletions' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-DAYS-7', value: 7, goal: 'Earn Daily 100% on 7 days.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-DAYS-21', value: 21, goal: 'Earn Daily 100% on 21 days.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-DAYS-60', value: 60, goal: 'Earn Daily 100% on 60 days.', reward: { gold: 200, xp: 1200, chest: 'Legendary' } },
      ],
    },
    {
      id: 'LIFE-WEEKS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Active weeks',
      tracking: { scope: 'lifetime', metric: 'weeklyPerfectCompletions' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-WEEKS-1', value: 1, goal: 'Earn Weekly 100% once.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-WEEKS-4', value: 4, goal: 'Earn Weekly 100% four times.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-WEEKS-12', value: 12, goal: 'Earn Weekly 100% twelve times.', reward: { gold: 200, xp: 1200, chest: 'Legendary' } },
      ],
    },
    {
      id: 'LIFE-SKILLS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Skills learned',
      tracking: { scope: 'lifetime', metric: 'skillsLearned' },
      stageLabel: 'Milestone',
      steps: [
        { id: 'LIFE-SKILLS-3', value: 3, goal: 'Log 3 skills learned.', reward: { gold: 25, xp: 150 } },
        { id: 'LIFE-SKILLS-6', value: 6, goal: 'Log 6 skills learned.', reward: { gold: 75, xp: 450, chest: 'Rare' } },
        { id: 'LIFE-SKILLS-12', value: 12, goal: 'Log 12 skills learned.', reward: { gold: 200, xp: 1200, chest: 'Legendary' } },
      ],
    },
    {
      id: 'growth-levels',
      type: 'section',
      title: 'Level questlines',
      subtitle: 'Unlocks at the indicated level; combine auto and manual steps.',
    },
    {
      id: 'L5-ENGINE',
      type: 'chain',
      category: 'Level 5 unlock',
      title: 'Application Engine',
      subtitle: 'Unlocks at level 5.',
      unlockLevel: 5,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L5-ENGINE-1',
          goal: 'Create a cover letter template.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl5_cover_template', goal: 1 },
        },
        {
          id: 'L5-ENGINE-2',
          goal: 'Build CV snippets.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl5_cv_snippets', goal: 1 },
        },
        {
          id: 'L5-ENGINE-3',
          goal: 'Define your follow-up cadence.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl5_followup_cadence', goal: 1 },
        },
      ],
    },
    {
      id: 'L5-CONFIDENCE',
      type: 'chain',
      category: 'Level 5 unlock',
      title: 'Confidence Circuit',
      subtitle: 'Unlocks at level 5.',
      unlockLevel: 5,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L5-CONFIDENCE-1',
          goal: 'Rehearse your interview pitch.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl5_pitch_rehearsal', goal: 1 },
        },
        {
          id: 'L5-CONFIDENCE-2',
          goal: 'Collect feedback from a peer.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl5_feedback_collect', goal: 1 },
        },
        {
          id: 'L5-CONFIDENCE-3',
          goal: 'Record an elevator pitch video.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl5_pitch_video', goal: 1 },
        },
      ],
    },
    {
      id: 'L10-RADAR',
      type: 'chain',
      category: 'Level 10 unlock',
      title: 'Opportunity Radar',
      subtitle: 'Unlocks at level 10.',
      unlockLevel: 10,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L10-RADAR-1',
          goal: 'Analyze target roles.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl10_role_analysis', goal: 1 },
        },
        {
          id: 'L10-RADAR-2',
          goal: 'Map in-demand skills.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl10_skill_map', goal: 1 },
        },
        {
          id: 'L10-RADAR-3',
          goal: 'Set alerts on 5 platforms.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl10_platform_alerts', goal: 1 },
        },
        {
          id: 'L10-RADAR-4',
          goal: 'Create a weekly review ritual.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl10_weekly_review', goal: 1 },
        },
      ],
    },
    {
      id: 'L10-BRAND',
      type: 'chain',
      category: 'Level 10 unlock',
      title: 'Brand Boost',
      subtitle: 'Unlocks at level 10.',
      unlockLevel: 10,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L10-BRAND-1',
          goal: 'Update your LinkedIn headline.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl10_linkedin_headline', goal: 1 },
        },
        {
          id: 'L10-BRAND-2',
          goal: 'Publish an insight post.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl10_insight_post', goal: 1 },
        },
        {
          id: 'L10-BRAND-3',
          goal: 'Gather three testimonials.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl10_testimonials', goal: 3 },
        },
      ],
    },
    {
      id: 'L20-CRED',
      type: 'chain',
      category: 'Level 20 unlock',
      title: 'Credibility Sprint',
      subtitle: 'Unlocks at level 20.',
      unlockLevel: 20,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L20-CRED-1',
          goal: 'Shortlist relevant certifications.',
          reward: { gold: 15, xp: 75 },
          tracking: { scope: 'manual', manualKey: 'lvl20_cert_shortlist', goal: 1 },
        },
        {
          id: 'L20-CRED-2',
          goal: 'Enroll in or complete one certification.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'manual', manualKey: 'lvl20_cert_enroll', goal: 1 },
        },
        {
          id: 'L20-CRED-3',
          goal: 'Showcase the credential publicly.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl20_cert_showcase', goal: 1 },
        },
      ],
    },
    {
      id: 'L20-NETWORK',
      type: 'chain',
      category: 'Level 20 unlock',
      title: 'Network Architecture',
      subtitle: 'Unlocks at level 20.',
      unlockLevel: 20,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L20-NETWORK-1',
          goal: 'Map your top 20 contacts.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl20_contacts_map', goal: 1 },
        },
        {
          id: 'L20-NETWORK-2',
          goal: 'Schedule five reconnects.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl20_reconnects', goal: 5 },
        },
        {
          id: 'L20-NETWORK-3',
          goal: 'Host a mini mastermind.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'manual', manualKey: 'lvl20_mastermind', goal: 1 },
        },
      ],
    },
    {
      id: 'L35-THOUGHT',
      type: 'chain',
      category: 'Level 35 unlock',
      title: 'Thought Leadership',
      subtitle: 'Unlocks at level 35.',
      unlockLevel: 35,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L35-THOUGHT-1',
          goal: 'Outline your signature talk.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl35_talk_outline', goal: 1 },
        },
        {
          id: 'L35-THOUGHT-2',
          goal: 'Deliver a webinar or live session.',
          reward: { gold: 35, xp: 175 },
          tracking: { scope: 'manual', manualKey: 'lvl35_webinar', goal: 1 },
        },
        {
          id: 'L35-THOUGHT-3',
          goal: 'Repurpose the recording into an article.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl35_article', goal: 1 },
        },
      ],
    },
    {
      id: 'L35-MENTOR',
      type: 'chain',
      category: 'Level 35 unlock',
      title: 'Mentor Loop',
      subtitle: 'Unlocks at level 35.',
      unlockLevel: 35,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L35-MENTOR-1',
          goal: 'Identify a mentor.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl35_mentor_find', goal: 1 },
        },
        {
          id: 'L35-MENTOR-2',
          goal: 'Set a monthly sync.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl35_monthly_sync', goal: 1 },
        },
        {
          id: 'L35-MENTOR-3',
          goal: 'Document an action plan.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl35_action_plan', goal: 1 },
        },
      ],
    },
    {
      id: 'L50-MARKET',
      type: 'chain',
      category: 'Level 50 unlock',
      title: 'Market Expansion',
      subtitle: 'Unlocks at level 50.',
      unlockLevel: 50,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L50-MARKET-1',
          goal: 'Research three new cities.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl50_city_research', goal: 3 },
        },
        {
          id: 'L50-MARKET-2',
          goal: 'Tailor a CV for each new city.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'lifetime', metric: 'tailoredCVs', goal: 3 },
        },
        {
          id: 'L50-MARKET-3',
          goal: 'Run salary benchmarking.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'manual', manualKey: 'lvl50_salary_benchmark', goal: 1 },
        },
        {
          id: 'L50-MARKET-4',
          goal: 'Apply to five roles per city.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'lifetime', metric: 'applications', goal: 15 },
        },
      ],
    },
    {
      id: 'L50-NEGOTIATION',
      type: 'chain',
      category: 'Level 50 unlock',
      title: 'Negotiation Mastery',
      subtitle: 'Unlocks at level 50.',
      unlockLevel: 50,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L50-NEGOTIATION-1',
          goal: 'Study a negotiation framework.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl50_negotiation_framework', goal: 1 },
        },
        {
          id: 'L50-NEGOTIATION-2',
          goal: 'Draft your BATNA.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl50_batna', goal: 1 },
        },
        {
          id: 'L50-NEGOTIATION-3',
          goal: 'Simulate a negotiation.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl50_negotiation_sim', goal: 1 },
        },
      ],
    },
    {
      id: 'L70-RUNWAY',
      type: 'chain',
      category: 'Level 70 unlock',
      title: 'Career Runway',
      subtitle: 'Unlocks at level 70.',
      unlockLevel: 70,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L70-RUNWAY-1',
          goal: 'Design a two-year career plan.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl70_plan', goal: 1 },
        },
        {
          id: 'L70-RUNWAY-2',
          goal: 'Identify future skills to learn.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl70_future_skills', goal: 1 },
        },
        {
          id: 'L70-RUNWAY-3',
          goal: 'Enroll in a long-form program.',
          reward: { gold: 40, xp: 200 },
          tracking: { scope: 'manual', manualKey: 'lvl70_long_form', goal: 1 },
        },
      ],
    },
    {
      id: 'L70-COMMUNITY',
      type: 'chain',
      category: 'Level 70 unlock',
      title: 'Community Builder',
      subtitle: 'Unlocks at level 70.',
      unlockLevel: 70,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L70-COMMUNITY-1',
          goal: 'Start a peer accountability group.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl70_group_start', goal: 1 },
        },
        {
          id: 'L70-COMMUNITY-2',
          goal: 'Host four accountability sessions.',
          reward: { gold: 25, xp: 125 },
          tracking: { scope: 'manual', manualKey: 'lvl70_group_session', goal: 4 },
        },
        {
          id: 'L70-COMMUNITY-3',
          goal: 'Create a shared resource bank.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl70_resource_bank', goal: 1 },
        },
      ],
    },
    {
      id: 'L100-LEGACY',
      type: 'chain',
      category: 'Level 100 unlock',
      title: 'Legacy Builder',
      subtitle: 'Unlocks at level 100.',
      unlockLevel: 100,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L100-LEGACY-1',
          goal: 'Mentor three job seekers.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'manual', manualKey: 'lvl100_mentor', goal: 3 },
        },
        {
          id: 'L100-LEGACY-2',
          goal: 'Publish your playbook.',
          reward: { gold: 40, xp: 200 },
          tracking: { scope: 'manual', manualKey: 'lvl100_playbook', goal: 1 },
        },
        {
          id: 'L100-LEGACY-3',
          goal: 'Contribute to an open career resource.',
          reward: { gold: 30, xp: 150 },
          tracking: { scope: 'manual', manualKey: 'lvl100_open_resource', goal: 1 },
        },
      ],
    },
    {
      id: 'L100-IMPACT',
      type: 'chain',
      category: 'Level 100 unlock',
      title: 'Impact Investor',
      subtitle: 'Unlocks at level 100.',
      unlockLevel: 100,
      stageLabel: 'Task',
      steps: [
        {
          id: 'L100-IMPACT-1',
          goal: 'Allocate a success bonus to professional growth.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl100_bonus_allocation', goal: 1 },
        },
        {
          id: 'L100-IMPACT-2',
          goal: 'Sponsor a community event.',
          reward: { gold: 40, xp: 200 },
          tracking: { scope: 'manual', manualKey: 'lvl100_sponsor_event', goal: 1 },
        },
        {
          id: 'L100-IMPACT-3',
          goal: 'Document your learnings.',
          reward: { gold: 20, xp: 100 },
          tracking: { scope: 'manual', manualKey: 'lvl100_learnings', goal: 1 },
        },
      ],
    },
  ],
  Events: [
    {
      id: 'events-overview',
      type: 'note',
      title: 'Dynamic events',
      notes: [
        'Events trigger automatically from your play patterns.',
        'Complete the tasks before the timer ends to claim the reward.',
      ],
    },
    {
      id: 'E-CANTSTOPME',
      type: 'event',
      title: "Can't Stop Me",
      trigger: 'Log 3 rejections in a single day.',
      triggerMeta: { scope: 'daily', metric: 'rejections', threshold: 3 },
      duration: '24 hours',
      durationHours: 24,
      tasks: [
        {
          id: 'E-CANTSTOPME-TASK1',
          goal: 'Submit 5 additional applications today.',
          tracking: { scope: 'event', metric: 'applications', goal: 5, reference: 'E-CANTSTOPME' },
        },
        {
          id: 'E-CANTSTOPME-TASK2',
          goal: 'Complete 1 additional full application today.',
          tracking: { scope: 'event', metric: 'fullApplications', goal: 1, reference: 'E-CANTSTOPME' },
        },
      ],
      reward: { gold: 25, xp: 125 },
    },
    {
      id: 'E-GHOSTSREVENGE',
      type: 'event',
      title: "Ghost's Revenge",
      trigger: 'Log 10 ghosted applications in a week.',
      triggerMeta: { scope: 'weekly', metric: 'ghosted', threshold: 10 },
      duration: '24 hours',
      durationHours: 24,
      cooldown: '7 days',
      cooldownHours: 168,
      tasks: [
        {
          id: 'E-GHOSTSREVENGE-TASK1',
          goal: 'Submit 10 applications within 24 hours.',
          tracking: { scope: 'event', metric: 'applications', goal: 10, reference: 'E-GHOSTSREVENGE' },
        },
        {
          id: 'E-GHOSTSREVENGE-TASK2',
          goal: 'Complete 5 full applications within 24 hours.',
          tracking: { scope: 'event', metric: 'fullApplications', goal: 5, reference: 'E-GHOSTSREVENGE' },
        },
        {
          id: 'E-GHOSTSREVENGE-TASK3',
          goal: 'Send 3 follow-ups within 24 hours.',
          tracking: { scope: 'event', metric: 'followUps', goal: 3, reference: 'E-GHOSTSREVENGE', manualKey: 'event_followup' },
        },
      ],
      reward: { gold: 25, xp: 125, effect: 'GhostsRevenge (2x XP & gold for 24h)' },
      notes: ['Cooldown: 1 per week. Effect activates immediately on claim.'],
    },
    {
      id: 'E-PERSIST-I',
      type: 'event',
      title: 'Persistent Spirit I',
      trigger: 'Mark an application as favorite.',
      triggerMeta: { scope: 'lifetime', metric: 'favorites', threshold: 1 },
      duration: '5 days',
      durationHours: 120,
      tasks: [
        {
          id: 'E-PERSIST-I-TASK1',
          goal: 'Send at least one follow-up.',
          tracking: { scope: 'event', metric: 'followUps', goal: 1, reference: 'E-PERSIST-I', manualKey: 'event_followup' },
        },
      ],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-PERSIST-II',
      type: 'event',
      title: 'Persistent Spirit II',
      trigger: 'Complete Persistent Spirit I.',
      triggerMeta: { scope: 'event', metric: 'E-PERSIST-I', threshold: 1 },
      duration: '10 days',
      durationHours: 240,
      tasks: [
        {
          id: 'E-PERSIST-II-TASK1',
          goal: 'Send a second follow-up.',
          tracking: { scope: 'event', metric: 'followUps', goal: 1, reference: 'E-PERSIST-II', manualKey: 'event_followup' },
        },
      ],
      reward: { gold: 0, xp: 0, chest: 'Legendary' },
      notes: ['Requires Persistent Spirit I to be completed.'],
    },
    {
      id: 'E-MOMENTUMTHAW',
      type: 'event',
      title: 'Momentum Thaw',
      trigger: 'Break a 48 hour hiatus after a 3 day streak.',
      triggerMeta: { scope: 'lifetime', metric: 'hiatus', threshold: 48 },
      duration: '12 hours',
      durationHours: 12,
      tasks: [
        {
          id: 'E-MOMENTUMTHAW-TASK1',
          goal: 'Log 3 applications within 2 hours.',
          tracking: { scope: 'event', metric: 'applicationsBurst', goal: 3, reference: 'E-MOMENTUMTHAW' },
        },
      ],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'E-OPPSURGE',
      type: 'event',
      title: 'Opportunity Surge',
      trigger: 'Flag 3 hot listings in a day.',
      triggerMeta: { scope: 'daily', metric: 'hotListings', threshold: 3 },
      duration: '24 hours',
      durationHours: 24,
      tasks: [
        {
          id: 'E-OPPSURGE-TASK1',
          goal: 'Apply to all flagged hot listings.',
          tracking: { scope: 'event', metric: 'hotApplications', goal: 3, reference: 'E-OPPSURGE' },
        },
        {
          id: 'E-OPPSURGE-TASK2',
          goal: 'Complete 2 additional full applications today.',
          tracking: { scope: 'event', metric: 'fullApplications', goal: 2, reference: 'E-OPPSURGE' },
        },
      ],
      reward: { gold: 25, xp: 125 },
    },
    {
      id: 'E-QUALITY-RECOVERY',
      type: 'event',
      title: 'Quality Recovery',
      trigger: 'Spray debuff becomes active.',
      triggerMeta: { scope: 'lifetime', metric: 'sprayDebuff', threshold: 1 },
      duration: '24 hours',
      durationHours: 24,
      tasks: [
        {
          id: 'E-QUALITY-RECOVERY-TASK1',
          goal: 'Submit 3 applications with quality score 2 or higher.',
          tracking: { scope: 'event', metric: 'qualityApplications', goal: 3, reference: 'E-QUALITY-RECOVERY' },
        },
      ],
      reward: { gold: 15, xp: 75, cleanse: 'Spray debuff' },
    },
    {
      id: 'E-REFERRAL-WINDOW',
      type: 'event',
      title: 'Referral Window',
      trigger: 'Log a referral contact.',
      triggerMeta: { scope: 'lifetime', metric: 'referralContacts', threshold: 1 },
      duration: '24 hours',
      durationHours: 24,
      tasks: [
        {
          id: 'E-REFERRAL-WINDOW-TASK1',
          goal: 'Submit one referral application.',
          tracking: { scope: 'event', metric: 'referralApplications', goal: 1, reference: 'E-REFERRAL-WINDOW' },
        },
      ],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-INTERVIEW-AFTERCARE',
      type: 'event',
      title: 'Interview Aftercare',
      trigger: 'Application status changes to Interview.',
      triggerMeta: { scope: 'lifetime', metric: 'interviews', threshold: 1 },
      duration: '48 hours',
      durationHours: 48,
      tasks: [
        {
          id: 'E-INTERVIEW-AFTERCARE-TASK1',
          goal: 'Send a thank-you note.',
          tracking: { scope: 'event', metric: 'thankYous', goal: 1, reference: 'E-INTERVIEW-AFTERCARE', manualKey: 'event_thankyou' },
        },
        {
          id: 'E-INTERVIEW-AFTERCARE-TASK2',
          goal: 'Make the next application a full application.',
          tracking: { scope: 'event', metric: 'fullApplications', goal: 1, reference: 'E-INTERVIEW-AFTERCARE' },
        },
      ],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-OFFER-LEVERAGE',
      type: 'event',
      title: 'Offer Leverage',
      trigger: 'Receive an offer.',
      triggerMeta: { scope: 'lifetime', metric: 'offers', threshold: 1 },
      duration: '72 hours',
      durationHours: 72,
      tasks: [
        {
          id: 'E-OFFER-LEVERAGE-TASK1',
          goal: 'Complete a market comparison.',
          tracking: { scope: 'event', metric: 'marketComparison', goal: 1, reference: 'E-OFFER-LEVERAGE', manualKey: 'event_market_comparison' },
        },
        {
          id: 'E-OFFER-LEVERAGE-TASK2',
          goal: 'Submit 5 additional applications within 72 hours.',
          tracking: { scope: 'event', metric: 'applications', goal: 5, reference: 'E-OFFER-LEVERAGE' },
        },
      ],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'E-BOUNCEBACK',
      type: 'event',
      title: 'Bounce Back',
      trigger: 'Two consecutive offers declined by the employer.',
      triggerMeta: { scope: 'lifetime', metric: 'offersDeclinedByEmployer', threshold: 2 },
      duration: '24 hours',
      durationHours: 24,
      tasks: [
        {
          id: 'E-BOUNCEBACK-TASK1',
          goal: 'Audit rejection feedback.',
          tracking: { scope: 'event', metric: 'reflectionNotes', goal: 1, reference: 'E-BOUNCEBACK', manualKey: 'event_feedback_audit' },
        },
        {
          id: 'E-BOUNCEBACK-TASK2',
          goal: 'Submit a revised full application.',
          tracking: { scope: 'event', metric: 'fullApplications', goal: 1, reference: 'E-BOUNCEBACK' },
        },
      ],
      reward: { gold: 20, xp: 100 },
      actions: [{ type: 'log', key: 'event_feedback_audit', label: 'Log audit note' }],
    },
    {
      id: 'E-FLASH-REFERRAL',
      type: 'event',
      title: 'Flash Referral',
      trigger: 'Receive a referral reply.',
      triggerMeta: { scope: 'lifetime', metric: 'referralReplies', threshold: 1 },
      duration: 'Same day',
      durationHours: 24,
      tasks: [
        {
          id: 'E-FLASH-REFERRAL-TASK1',
          goal: 'Schedule a conversation within 24 hours.',
          tracking: { scope: 'event', metric: 'meetings', goal: 1, reference: 'E-FLASH-REFERRAL', manualKey: 'event_schedule_convo' },
        },
        {
          id: 'E-FLASH-REFERRAL-TASK2',
          goal: 'Log a recap after the conversation.',
          tracking: { scope: 'event', metric: 'recaps', goal: 1, reference: 'E-FLASH-REFERRAL', manualKey: 'event_convo_recap' },
        },
      ],
      reward: { gold: 15, xp: 75 },
      actions: [
        { type: 'log', key: 'event_schedule_convo', label: 'Log schedule' },
        { type: 'log', key: 'event_convo_recap', label: 'Log recap' },
      ],
      notes: ['Calendar integration can automate this when available; otherwise use quick logs.'],
    },
  ],
};
