export const QUESTS = {
  Daily: [
    {
      id: 'daily-definitions',
      type: 'note',
      title: 'Key definitions',
      notes: [
        'Full application = Type set to "Full" with both a tailored CV and motivation letter.',
        'Daily 100% = finish every Daily core quest.',
        'Weekly 100% = finish every Weekly core quest.',
        'Platform diversity (daily) = use 3+ distinct platforms today.',
        'Platform diversity (weekly) = use 6+ distinct platforms this week.',
      ],
    },
    {
      id: 'D-APPS',
      type: 'tiered',
      category: 'Daily core quest',
      title: 'Apply today',
      desc: 'Quantity drive',
      incremental: true,
      tiers: [
        {
          goal: 'Submit 10 applications today.',
          reward: { gold: 10, xp: 50 },
        },
        {
          goal: 'Submit 15 applications today.',
          reward: { gold: 10, xp: 50 },
        },
        {
          goal: 'Submit 20 applications today.',
          reward: { gold: 10, xp: 50 },
        },
      ],
      notes: ['Rewards stack because the quest is incremental (total 30g / 150 XP).'],
    },
    {
      id: 'D-FULL',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Full applications',
      desc: 'Depth matters',
      goals: ['Submit ≥5 full applications today.'],
      reward: { gold: 20, xp: 100 },
      notes: ['Full application uses the definition above.'],
    },
    {
      id: 'D-PLATFORMS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Platform diversity',
      goals: ['Use ≥3 distinct job platforms today.'],
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-CVS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Tailored CVs',
      goals: ['Tailor ≥5 CVs today.'],
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-LETTERS',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Letters of motivation',
      goals: ['Write ≥5 motivation letters today.'],
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-COLD',
      type: 'standard',
      category: 'Daily core quest',
      title: 'Cold approaches',
      goals: ['Complete ≥2 cold approaches today (LinkedIn or other).'],
      reward: { gold: 10, xp: 50 },
    },
    {
      id: 'D-PERFECT',
      type: 'standard',
      category: 'Daily mastery',
      title: 'Daily 100%',
      goals: ['Complete every other Daily quest.'],
      reward: { gold: 20, xp: 100 },
      lock: 'Auto-completes only if all other Daily quests are done.',
    },
  ],
  Weekly: [
    {
      id: 'weekly-overview',
      type: 'note',
      title: 'Weekly structure',
      notes: [
        'Core quests reset each week. Finish them all to unlock Weekly 100%.',
        'Cyclable slots per week: 2. Pick the quests that match your strategy.',
      ],
    },
    {
      id: 'weekly-core',
      type: 'section',
      title: 'Core quests',
      subtitle: 'Complete the full set to earn Weekly 100%.',
    },
    {
      id: 'W-APPS80',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly volume',
      goals: ['Submit ≥80 applications this week.'],
      reward: { gold: 50, xp: 250 },
    },
    {
      id: 'W-FULL35',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly full apps',
      goals: ['Submit ≥35 full applications this week.'],
      reward: { gold: 30, xp: 150 },
      notes: ['Full application uses the definition above.'],
    },
    {
      id: 'W-PLATFORMS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Weekly platform diversity',
      goals: ['Use ≥6 distinct platforms this week.'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'W-STREAK',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Daily streaks',
      goals: ['Earn Daily 100% on ≥4 days this week.'],
      reward: { gold: 20, xp: 100 },
      notes: ['Daily streaks track your Daily 100% completions.'],
    },
    {
      id: 'W-CVS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Tailored CVs (weekly)',
      goals: ['Tailor ≥25 CVs this week.'],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'W-LETTERS',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'Motivation letters (weekly)',
      goals: ['Write ≥25 motivation letters this week.'],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'W-SKILL',
      type: 'standard',
      category: 'Weekly core quest',
      title: 'New skill',
      goals: ['Complete ≥1 new skill item (micro-course, guided project, or skill module).'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'W-PERFECT',
      type: 'standard',
      category: 'Weekly mastery',
      title: 'Weekly 100%',
      goals: ['Complete every Weekly core quest.'],
      reward: { gold: 30, xp: 150, chest: 'Rare' },
    },
    {
      id: 'weekly-cyclable',
      type: 'section',
      title: 'Cyclable quests',
      subtitle: 'Pick any 2 each week (slots available: 2).',
    },
    {
      id: 'WC-RECRUITERS',
      type: 'standard',
      category: 'Weekly cyclable',
      title: 'Recruiter outreach',
      goals: ['Reach out to ≥10 recruiters this week.'],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'WC-AGENCIES',
      type: 'standard',
      category: 'Weekly cyclable',
      title: 'Agency touchpoints',
      goals: ['Contact ≥3 agencies this week.'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'WC-NETWORK',
      type: 'standard',
      category: 'Weekly cyclable',
      title: 'Network pings',
      goals: ['Request ≥3 friend introductions this week.'],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'WC-CITIES',
      type: 'standard',
      category: 'Weekly cyclable',
      title: 'City diversity',
      goals: ['Target roles across ≥4 distinct cities this week.'],
      reward: { gold: 20, xp: 100 },
    },
  ],
  Growth: [
    {
      id: 'growth-overview',
      type: 'note',
      title: 'Long-term mastery',
      notes: ['Milestone chains reward lifetime effort while level lines unlock new systems as you progress.'],
    },
    {
      id: 'growth-chains',
      type: 'section',
      title: 'Milestone chains',
      subtitle: 'Track lifetime totals to unlock escalating rewards.',
    },
    {
      id: 'G-APPS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime applications',
      steps: [
        { goal: 'Reach ≥100 lifetime applications.', reward: { gold: 25, xp: 125, chest: 'Common' } },
        { goal: 'Reach ≥250 lifetime applications.', reward: { gold: 50, xp: 250, chest: 'Rare' } },
        { goal: 'Reach ≥500 lifetime applications.', reward: { gold: 100, xp: 500, chest: 'Epic' } },
        { goal: 'Reach ≥1000 lifetime applications.', reward: { gold: 250, xp: 1250, chest: 'Legendary' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-FULL',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime full apps',
      steps: [
        { goal: 'Reach ≥50 lifetime full applications.', reward: { gold: 30, xp: 150 } },
        { goal: 'Reach ≥150 lifetime full applications.', reward: { gold: 80, xp: 400 } },
        { goal: 'Reach ≥300 lifetime full applications.', reward: { gold: 150, xp: 750, chest: 'Epic' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-QUALITY',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Full+CV+Letter combos',
      steps: [
        { goal: 'Complete ≥25 full + CV + letter combos overall.', reward: { gold: 25, xp: 125 } },
        { goal: 'Complete ≥75 full + CV + letter combos overall.', reward: { gold: 75, xp: 375 } },
        { goal: 'Complete ≥150 full + CV + letter combos overall.', reward: { gold: 150, xp: 750, chest: 'Rare' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-CVS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime tailored CVs',
      steps: [
        { goal: 'Tailor ≥50 CVs in total.', reward: { gold: 25, xp: 125 } },
        { goal: 'Tailor ≥150 CVs in total.', reward: { gold: 75, xp: 375 } },
        { goal: 'Tailor ≥300 CVs in total.', reward: { gold: 150, xp: 750 } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-LETTERS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Lifetime motivation letters',
      steps: [
        { goal: 'Write ≥50 motivation letters overall.', reward: { gold: 25, xp: 125 } },
        { goal: 'Write ≥150 motivation letters overall.', reward: { gold: 75, xp: 375 } },
        { goal: 'Write ≥300 motivation letters overall.', reward: { gold: 150, xp: 750 } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-CITIES',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Market coverage',
      steps: [
        { goal: 'Apply across ≥10 distinct cities overall.', reward: { gold: 25, xp: 125 } },
        { goal: 'Apply across ≥20 distinct cities overall.', reward: { gold: 75, xp: 375 } },
        { goal: 'Apply across ≥35 distinct cities overall.', reward: { gold: 150, xp: 750 } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-ACTIVEDAYS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Active days (100% daily)',
      steps: [
        { goal: 'Finish Daily 100% on ≥7 total days.', reward: { gold: 25, xp: 125 } },
        { goal: 'Finish Daily 100% on ≥21 total days.', reward: { gold: 75, xp: 375, chest: 'Rare' } },
        { goal: 'Finish Daily 100% on ≥60 total days.', reward: { gold: 200, xp: 1000, chest: 'Epic' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-ACTIVEWEEKS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Active weeks (100% weekly)',
      steps: [
        { goal: 'Finish Weekly 100% on ≥1 total week.', reward: { gold: 25, xp: 125 } },
        { goal: 'Finish Weekly 100% on ≥4 total weeks.', reward: { gold: 75, xp: 375 } },
        { goal: 'Finish Weekly 100% on ≥12 total weeks.', reward: { gold: 200, xp: 1000, chest: 'Legendary' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'G-SKILLS',
      type: 'chain',
      category: 'Milestone chain',
      title: 'Skills learned',
      steps: [
        { goal: 'Learn ≥3 skills in total.', reward: { gold: 25, xp: 125 } },
        { goal: 'Learn ≥6 skills in total.', reward: { gold: 75, xp: 375 } },
        { goal: 'Learn ≥12 skills in total.', reward: { gold: 200, xp: 1000, chest: 'Epic' } },
      ],
      stageLabel: 'Step',
    },
    {
      id: 'growth-levels',
      type: 'section',
      title: 'Level unlock lines',
      subtitle: 'Reach the indicated level to unlock these questlines.',
    },
    {
      id: 'L3-PORTFOLIO',
      type: 'chain',
      category: 'Level 3 unlock',
      title: 'Portfolio v1',
      subtitle: 'Unlocks at level 3',
      steps: [
        { goal: 'Build a case study.', reward: { gold: 25, xp: 125 } },
        { goal: 'Publish your portfolio.', reward: { gold: 25, xp: 125, chest: 'Common' } },
      ],
      stageLabel: 'Task',
    },
    {
      id: 'L5-FASTSYSTEMS',
      type: 'chain',
      category: 'Level 5 unlock',
      title: 'Speed systems',
      subtitle: 'Unlocks at level 5',
      steps: [
        { goal: 'Create a cover letter template.', reward: { gold: 25, xp: 125 } },
        { goal: 'Create CV tailoring snippets.', reward: { gold: 25, xp: 125 } },
        { goal: 'Set a follow-up pipeline.', reward: { gold: 25, xp: 125 } },
      ],
      stageLabel: 'Task',
    },
    {
      id: 'L7-MARKET',
      type: 'chain',
      category: 'Level 7 unlock',
      title: 'Job market analysis',
      subtitle: 'Unlocks at level 7',
      steps: [
        { goal: 'Analyze top target titles.', reward: { gold: 25, xp: 125 } },
        { goal: 'Map in-demand skills.', reward: { gold: 25, xp: 125 } },
        { goal: 'Build a skill gap plan.', reward: { gold: 50, xp: 250, chest: 'Rare' } },
      ],
      stageLabel: 'Task',
    },
    {
      id: 'L9-CRED',
      type: 'chain',
      category: 'Level 9 unlock',
      title: 'Cred build',
      subtitle: 'Unlocks at level 9',
      steps: [
        { goal: 'Earn a certification.', reward: { gold: 50, xp: 250 } },
        { goal: 'Publish 2 showcase posts.', reward: { gold: 50, xp: 250, chest: 'Epic' } },
      ],
      stageLabel: 'Task',
    },
  ],
  Events: [
    {
      id: 'events-overview',
      type: 'note',
      title: 'Dynamic events',
      notes: [
        'Events trigger automatically from your play patterns.',
        'Complete the tasks before the timer ends to claim the reward.',
      ],
    },
    {
      id: 'E-CANTSTOPME',
      type: 'event',
      title: "Can't stop me",
      goals: ['Push through the setbacks.'],
      trigger: 'Log ≥3 rejections in a single day.',
      duration: '24 hours',
      tasks: [
        'Submit ≥5 additional applications today.',
        'Complete ≥1 additional full application today.',
      ],
      reward: { gold: 25, xp: 125 },
    },
    {
      id: 'E-GHOSTSREVENGE',
      type: 'event',
      title: "Ghost's revenge",
      trigger: 'Log ≥10 ghosted applications this week.',
      duration: '24 hours',
      tasks: [
        'Submit ≥10 applications within 24 hours.',
        'Complete ≥5 full applications within 24 hours.',
        'Send ≥3 follow-ups within 24 hours.',
      ],
      reward: { effect: 'GhostsRevenge (2x XP & gold for 24h)', gold: 25, xp: 125 },
      notes: ['Cooldown: 1/week.'],
    },
    {
      id: 'E-PERSIST-I',
      type: 'event',
      title: 'Persistent spirit I',
      trigger: 'Mark an application as favorite.',
      duration: '5 days',
      tasks: ['Send at least 1 follow-up.'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-PERSIST-II',
      type: 'event',
      title: 'Persistent spirit II',
      trigger: 'Complete Persistent spirit I.',
      duration: '10 days',
      tasks: ['Send a second follow-up.'],
      reward: { chest: 'Legendary', gold: 0, xp: 0 },
      notes: ['Requires Persistent spirit I to be completed.'],
    },
    {
      id: 'E-MOMENTUMFREEZE',
      type: 'event',
      title: 'Momentum thaw',
      trigger: 'No applications logged for ≥48 hours with a prior 3+ day streak.',
      duration: '12 hours',
      tasks: ['Log ≥3 applications within 2 hours.'],
      reward: { gold: 20, xp: 100 },
    },
    {
      id: 'E-OPPSURGE',
      type: 'event',
      title: 'Opportunity surge',
      trigger: 'Detect ≥3 hot listings today.',
      duration: '24 hours',
      tasks: [
        'Apply to ≥3 hot listings today.',
        'Complete ≥2 additional full applications today.',
      ],
      reward: { gold: 25, xp: 125 },
    },
    {
      id: 'E-SPRAY-RECOVERY',
      type: 'event',
      title: 'Quality recovery',
      trigger: 'Spray debuff becomes active.',
      duration: '24 hours',
      tasks: ['Submit ≥3 applications with quality score ≥2 within 24 hours.'],
      reward: { gold: 15, xp: 75, cleanse: 'Spray debuff' },
    },
    {
      id: 'E-REFERRAL-WINDOW',
      type: 'event',
      title: 'Referral window',
      trigger: 'Log a referral contact.',
      duration: '24 hours',
      tasks: ['Submit 1 referral application.'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-INTERVIEW-AFTERCARE',
      type: 'event',
      title: 'Interview aftercare',
      trigger: 'Status changes to Interview.',
      duration: '48 hours',
      tasks: ['Send a thank-you note.', 'Submit the next application as a full application.'],
      reward: { gold: 15, xp: 75 },
    },
    {
      id: 'E-OFFER-LEVERAGE',
      type: 'event',
      title: 'Leverage the offer',
      trigger: 'Receive an offer.',
      duration: '72 hours',
      tasks: ['Complete a market comparison.', 'Submit ≥5 applications within 72 hours.'],
      reward: { gold: 20, xp: 100 },
    },
  ],
};
